Perro perritos[]={
{"Aska"," MastinEspanol",1,'h'},
{"Aisa","SanBernardo",2,'h'},
{"Bian","GaranDanes",3,'h'},
{"Bena","LeonBerger",4,'h'},
{"Cukita","Rottweiler",3,'h'},
{"Corela","AlaskanManlamut",2,'h'},
{"Amis", "Boxer", 1, 'm'},
{"Bolo","PastorAleman", 2, 'm'},
{"Bobby", "PastorIngles", 5, 'm'},
{"Casper", "Labrador", 7, 'm'},
{"Coco","Dalmata",3,'m'},
{"Valto","Bulldog",4,'m'},
{"Blacky","Labrador",1,'m'},
{"Dixie","Dalmata",2,'h'},
{"Flufli","Bulldog",3,'m'},
{"Elys","GranDanes",4,'h'},
{"Aska","Labrador",4,'h'},
{"Bena","LeonBerger",4,'h'},
{"Cukita","Rottweiler",3,'h'},
{"Corela","AlaskanManlamut",2,'h'},
{"Amis", "Boxer", 1, 'm'},
{"Bolo","PastorAleman", 9, 'm'},
{"Mordelon", "PastorIngles", 1, 'm'},
{"Rex", "Labrador", 8, 'm'},
{"Adam","Dalmata",7,'m'},
{"Pluto","Bulldog",5,'m'},
{"fofy", "PastorIngles", 4, 'm'},
{"Popy", "Labrador", 3, 'm'},
{"Scooby","Dalmata",3,'m'},
{"Ala","Bulldog",10,'m'},
{"Cacho"," MastinEspanol",0,'h'},
{"Dina","SanBernardo",2,'h'},
{"Mani","Belga",3,'h'},
{"Bena","Belga",0,'h'},
{"Axell","Rottweiler",0,'h'},
{"aandy","Sabueso",2,'h'},
{"Aika", "Husky", 1, 'm'},
{"Akira","Husky", 2, 'm'},
{"Alaska", "Husky", 5, 'm'},
{"ALEX", "Labrador", 0, 'm'},
{"Val","Dalmata",1,'m'},
{"Fito","Bulldog",1,'m'},
{"Flanky","Labrador",1,'m'},
{"Fluffly","Dalmata",0,'h'},
{"Frac","Bulldog",2,'m'},
{"Garys","GranDanes",0,'h'},
{"giro","Labrador",3,'h'},
{"gizmo","LeonBerger",0,'h'},
{"greta","Rottweiler",4,'h'},
{"Corela","AlaskanManlamut",0,'h'},
{"Nany", "Boxer", 1, 'm'},
{"Neko","PastorAleman", 5, 'm'},
{"Nora", "PastorIngles", 1, 'm'},
{"Rex", "Labrador", 8, 'm'},
{"Adam","Dalmata",9,'m'},
{"Pluto","Bulldog",2,'m'},
{"fofy", "PastorIngles", 2, 'h'},
{"Popy", "Labrador", 3, 'm'},
{"Scooby","Cesky",0,'m'},
{"Nina","Cesky",4,'h'}
};