Perro perritos[]={
{"Aska"," MastinEspanol",1,'h'},
{"Aisa","SanBernardo",2,'h'},
{"Bian","GaranDanes",3,'h'},
{"Bena","LeonBerger",4,'h'},
{"Cukita","Rottweiler",3,'h'},
{"Corela","AlaskanManlamut",2,'h'},
{"Amis", "Boxer", 1, 'm'},
{"Bolo","PastorAleman", 2, 'm'},
{"Bobby", "PastorIngles", 5, 'm'},
{"Casper", "Labrador", 7, 'm'},
{"Coco","Dalmata",3,'m'},
{"Valto","Bulldog",4,'m'},
{"Blacky","Labrador",1,'m'},
{"Dixie","Dalmata",2,'h'},
{"Flufli","Bulldog",3,'m'},
{"Elys","GranDanes",4,'h'},
{"Aska","Labrador",4,'h'},
{"Bena","LeonBerger",4,'h'},
{"Cukita","Rottweiler",3,'h'},
{"Corela","AlaskanManlamut",2,'h'},
{"Amis", "Boxer", 1, 'm'},
{"Bolo","PastorAleman", 9, 'm'},
{"Mordelon", "PastorIngles", 1, 'm'},
{"Rex", "Labrador", 8, 'm'},
{"Adam","Dalmata",7,'m'},
{"Pluto","Bulldog",5,'m'},
{"fofy", "PastorIngles", 4, 'm'},
{"Popy", "Labrador", 3, 'm'},
{"Scooby","Dalmata",3,'m'},
{"Ala","Bulldog",10,'m'}
};